worktime_project/urls.py
#coding=utf-8
"""project0 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import logout_then_login
from worktime.views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', custom_login, name='login'),
    url(r'^logout_then_login/$', logout_then_login, name='logout_then_login'),
    url(r'^tabel/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$', TabelView.as_view(), name='tabel'),
    url(r'^tabel_period_form/$', tabel_period_form, name='tabel_period_form'),
    url(r'tabel_json/$', tabel_json, name='tabel_json'),
    url(r'^tabel_period/(?P<start>\d+)/(?P<end>\d+)/(?P<id>\d+)/$', tabel_period, name='tabel_period'),
    url(r'^employee/$', employee_view, name='employee'),
    url(r'^employee_create/$', employee_create_view, name='employee_create'),
    url(r'^employee_update/(?P<pk>\d+)/$', employee_update_view, name='employee_update'),
    url(r'^employee_delete/(?P<pk>\d+)/$', EmployeeDeleteView.as_view(success_url='/employee/'), name='employee_delete'),
    url(r'^export_xlsx/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$', export_xlsx, name='export_xlsx'),
]

admin.site.site_header = 'Администрирование Worktime'
admin.site.title = 'Администрирование Worktime'
admin.site.index_title = 'Worktime'

worktime/models.py
# coding: utf8
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser

COMPANY = [
        ['Галс', 'Галс'],
        ['Водомат', 'Водомат'],
        ['Водомат-сервис', 'Водомат-сервис'],
        ['ХАВ', 'ХАВ'],
        ['Визит', 'Визит'],
    ]


class Employee(models.Model):

    company = models.CharField(max_length=20, choices=COMPANY, default='Галс', verbose_name='Компания')
    firstname = models.CharField(max_length=20, verbose_name='Имя')
    lastname = models.CharField(max_length=20, verbose_name='Фамилия')
    post = models.CharField(max_length=100, verbose_name='Должность')
    start_work = models.TimeField(default='10:30:00', verbose_name='Начало смены')
    end_work = models.TimeField(default='19:30:00', verbose_name='Конец смены')
    card = models.CharField(max_length=13, verbose_name='Карта сотрудника')

    def __unicode__(self):
        return '%s %s' % (self.lastname, self.firstname)

    class Meta:
        db_table = 'employee'
        ordering = ['lastname']
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'


class Tabel(models.Model):
    employee = models.ForeignKey(Employee, verbose_name='Сотрудник')
    start_work = models.DateTimeField(auto_now_add=True, verbose_name='Начало смены')
    end_work = models.DateTimeField(null=True, verbose_name='Конец смены')
    time_at_work = models.TimeField(null=True, verbose_name='Длительность смены')
    at_work = models.BooleanField(verbose_name='На работе')

    def __unicode__(self):
        return '%s' % self.employee

    class Meta:
        db_table = 'tabel'
        ordering = ['employee']
        verbose_name = 'Табель'
        verbose_name_plural = 'Табели'


class CustomUser(AbstractUser):
    company_permission = models.CharField(max_length=20, choices=COMPANY, default='Галс', verbose_name='Разрешенные компании')

worktime/forms.py
# coding: utf-8
from django import forms
from worktime.models import Employee


class jQueryUIWidget(forms.TextInput):

    class Media:
        css = {'all': ('//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css',)}
        js = ('https://code.jquery.com/jquery-1.12.4.js', 'https://code.jquery.com/ui/1.12.1/jquery-ui.js')


class AddCssClass(forms.Form):

    def __init__(self, *args, **kwargs):
        super(AddCssClass, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class PeriodForm(AddCssClass):

    # employee = forms.ModelChoiceField(queryset=Employee.objects.all().only('id', 'lastname'), label=u'Сотрудник')
    employee_label = forms.CharField(widget=jQueryUIWidget(attrs={'autofocus': 1}), label=u'Введите фамилию')
    employee = forms.IntegerField(widget=forms.HiddenInput)
    period = forms.CharField(label=u'Выберите период')

    def clean_period(self):
        data = self.cleaned_data['period']
        period = data.split('-')
        for data in period:
            if int(data[:2]) > 31 or int(data[2:4]) > 12 or int(data[:2]) < 1 or int(data[2:4]) < 1:
                raise forms.ValidationError('Неверный период!!!')
        if len(period) < 2:
            period.append(period[0])
        return period


class EmployeeUpdateForm(forms.ModelForm, AddCssClass):

    class Meta:
        model = Employee
        fields = ['company', 'firstname', 'lastname', 'post', 'start_work', 'end_work', 'card']


class EmployeeCreateForm(EmployeeUpdateForm):

    def __init__(self, *args, **kwargs):
        super(EmployeeCreateForm, self).__init__(*args, **kwargs)
        self.fields['card'].initial = '300000000'

    def clean_card(self):
        card = self.cleaned_data['card']
        if not len(card) == 13:
            raise forms.ValidationError('Некорректный номер карты!')
        try:
            employee = Employee.objects.get(card=card)
        except Employee.DoesNotExist:
            employee = None
        if employee:
            raise forms.ValidationError(u'Карта %s уже зарегистрирована на сотрудника %s!' % (card, employee))
        return card

worktime/views.py
# coding: utf-8

from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login
from django.views.generic.dates import DayArchiveView
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Employee, Tabel
from .models import COMPANY as all_company
from .forms import PeriodForm, EmployeeCreateForm, EmployeeUpdateForm
import datetime
from django.utils import timezone
import openpyxl
from .functions import time_delta, hello_message


def custom_login(request):
    username = request.POST['username']
    password = request.POST['password']
    date = datetime.date.today()
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return redirect('tabel', year=date.year, month=date.month, day=date.day)
    else:
        return redirect('index')


def index(request):
    if request.method == 'POST':
        card = request.POST['card']
        time = timezone.localtime(timezone.now())
        try:
            employee = Employee.objects.get(card=card)
        except Employee.DoesNotExist:
            return render(request, 'worktime/error.html')
        except Employee.MultipleObjectsReturned:
            return render(request, 'worktime/error.html', {'card': card})
        try:
            tabel = Tabel.objects.get(employee=employee, start_work__gte=datetime.date.today(), at_work=True)
            tabel.end_work = timezone.now()
            tabel.at_work = False
            tabel.time_at_work = time_delta(tabel.end_work - tabel.start_work)
            tabel.save()
            message = ['До свидания,', 'Всего хорошего,', 'До скорой встречи, ;)', 'До встречи,']
            return render(request, 'worktime/bye.html', {'employee': employee, 'message': message})
        except Tabel.DoesNotExist:
            tabel = Tabel(employee=employee, at_work=True)
            tabel.save()
            message = hello_message(time)
            return render(request, 'worktime/hello.html', {'employee': employee, 'message': message})
    return render(request, 'worktime/index.html')


class TabelView(LoginRequiredMixin, DayArchiveView):
    date_field = 'start_work'
    template_name = 'worktime/tabel.html'
    context_object_name = 'tabel_table'
    allow_empty = True
    allow_future = True
    month_format = '%m'

    def get_context_data(self, **kwargs):
        context = super(TabelView, self).get_context_data(**kwargs)
        context['company_list'] = [i[0] for i in all_company]
        return context

    def get_queryset(self):
        company_permission = self.request.user.company_permission
        if company_permission == u'Галс':
            company = self.request.GET.get('company')
            if company:
                return Tabel.objects.filter(employee__company=company)
            else:
                return Tabel.objects.all()
        else:
            return Tabel.objects.filter(employee__company=company_permission)


@login_required
def tabel_period_form(request):
    if request.method == 'POST':
        form = PeriodForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            return redirect('tabel_period', start=data['period'][0], end=data['period'][1], id=data['employee'])
    else:
        form = PeriodForm()
    return render(request, 'worktime/tabel_form.html', {'form': form})


@login_required
def tabel_json(request):
    term = request.GET['term'].capitalize()
    data = Employee.objects.filter(lastname__startswith=term)
    employees = []
    for employee in data:
        employee = {'value': str(employee), 'id': employee.id}
        employees.append(employee)
    return JsonResponse(employees, safe=False)


@login_required
def tabel_period(request, start, end, id):
    start = datetime.date(int(start[4:]), int(start[2:4]), int(start[:2]))
    end = datetime.datetime(int(end[4:]), int(end[2:4]), int(end[:2]), 23, 59)
    employee = Employee.objects.get(id=id)
    tabel_period = Tabel.objects.filter(employee=employee, start_work__range=(start, end))
    return render(request, 'worktime/tabel_period.html',
                  {'tabel_period': tabel_period, 'start': start, 'end': end, 'employee': employee})


@login_required
def employee_view(request):
    company_list = [i[0] for i in all_company]
    company = request.GET.get('company')
    lastname = request.GET.get('lastname')
    company_permission = request.user.company_permission
    if company_permission == u'Галс':
        if company:
            employee_table = Employee.objects.filter(company=company)
        elif lastname:
            employee_table = Employee.objects.filter(lastname__istartswith=lastname)
        else:
            employee_table = Employee.objects.all()
    else:
        if lastname:
            employee_table = Employee.objects.filter(company=company_permission).filter(lastname__istartswith=lastname)
        else:
            employee_table = Employee.objects.filter(company=company_permission)

    return render(request, 'worktime/employee.html', {'employee_table': employee_table, 'company_list': company_list})


@login_required
def employee_create_view(request):
    if request.method == 'POST':
        form = EmployeeCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('employee')
        else:
            return render(request, 'worktime/employee_create.html', {'form': form})
    else:
        form = EmployeeCreateForm()
        return render(request, 'worktime/employee_create.html', {'form': form})


@login_required
def employee_update_view(request, pk):
    employee = Employee.objects.get(id=pk)
    if request.method == 'POST':
        form = EmployeeUpdateForm(request.POST)
        if form.is_valid():
            form = EmployeeUpdateForm(request.POST, instance=employee)
            form.save()
            return redirect('employee')
        else:
            return render(request, 'worktime/employee_update.html', {'form': form})
    else:
        form = EmployeeUpdateForm(instance=employee)
        return render(request, 'worktime/employee_update.html', {'form': form})


class EmployeeDeleteView(LoginRequiredMixin, DeleteView):
    model = Employee
    template_name = 'worktime/employee_delete.html'


@login_required
def export_xlsx(request, year, month, day):
    date = datetime.date(int(year), int(month), int(day))
    tabel = Tabel.objects.filter(start_work__contains=date).order_by('employee')
    excel_data = [[u'Сотрудник', u'Начало смены', u'Конец смены', u'Длительность смены', 'Дата'],
                  ['', '', '', '', '']
                  ]
    for obj in tabel:
        if obj.end_work:
            end_work = '{}:{:0>2}'.format(timezone.localtime(obj.end_work).hour, obj.end_work.minute)
        else:
            end_work = ''
        excel_data.append([str(obj.employee),
                           '{}:{:0>2}'.format(timezone.localtime(obj.start_work).hour, obj.start_work.minute),
                           end_work,
                           str(obj.time_at_work),
                           str(obj.start_work.date())
                           ])
    wb = openpyxl.Workbook()
    ws = wb.get_active_sheet()
    ws.title = u'Табель %s' % date
    ws.column_dimensions['A'].width = 40
    ws.column_dimensions['B'].width = 15
    ws.column_dimensions['C'].width = 15
    ws.column_dimensions['D'].width = 20
    ws.column_dimensions['E'].width = 15
    for line in excel_data:
        ws.append(line)
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=%s.xlsx' % date

    wb.save(response)
    return response

templates/worktime/alphabet.html
{% block alphabet %}

    {% with letters='АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЭЮЯ' %}

        <div class="btn-toolbar">
        {% if 'tabel' not in request.path %}
            <div class="btn-group">
            {% for i in letters %}
                <a href="?lastname={{ i }}" class="btn btn-default">{{ i }}</a>
            {% endfor %}
            </div>
        {% endif %}

            <div class="btn-group dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Выбрать предприятие <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    {% for i in company_list %}
                        <li><a href="?company={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    {% endwith %}

    <br>

{% endblock %}

templates/worktime/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		{% block meta %}{% endblock %}
		<title>{% block title %}{% endblock %}</title>
		{{ form.media }}
        <link rel="stylesheet" href={%static "bootstrap/css/bootstrap.min.css" %}>
		<link rel='stylesheet' href="{% static 'worktime/css/style.css' %}">
		<link rel="shortcut icon" href="{% static 'worktime/img/favicon.png' %}" type="image/png">
        {% block static %}
            <script src="{% static 'worktime/js/jquery-3.2.1.min.js' %}"></script>
            <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
            <script src="{% static 'worktime/js/jquery.tablesorter.min.js' %}"></script>
        {% endblock %}
	</head>

	<body>

    {% now "Y" as current_year %}
    {% now "m" as current_month %}
    {% now "d" as current_day %}

		<nav class='navbar navbar-static-top'>
			<div class='container-fluid'>
				<div class='navbar-header'>
				    <a class='navbar-brand'>Worktime</a>
				</div>
				{% if user.is_authenticated %}
                    <div class='navbar-right' style='margin-right:10px'>
                        <p class='navbar-text'>{{ user.first_name }} {{ user.last_name }}</p>
                        <a href='{% url 'logout_then_login' %}' class='btn btn-default navbar-btn'>
                            <span class='glyphicon glyphicon-log-out'></span> Выйти
                        </a>
                    </div>
				{% else %}
				    <form action='{% url 'login' %}' method='post' class='navbar-form navbar-right'>
                        {% csrf_token %}
                        <div class='form-group'>
                            <input type='text' class='form-control' placeholder='Пользователь' name='username' autocomplete='off'>
                            <input type='password' class='form-control' placeholder='Пароль' name='password'>
                        </div>
                        <button type='submit' class='btn btn-default'>
                            <span class='glyphicon glyphicon-log-in'></span>  Войти
                        </button>
                    </form>
				{% endif %}
			</div>
		</nav>

		<div class='container-fluid'>
			<div class='row'>
                {% block menu %}
                    {% include 'worktime/menu.html' %}
                {% endblock %}

			    <div class='col-sm-offset-3 col-sm-9 col-md-offset-2 col-md-10 content'>
				    {% block content %}
				    {% endblock %}
			    </div>
			</div>
		</div>

	</body>
</html>

templates/worktime/bye.html
{% extends 'worktime/base.html' %}

{% block meta %}
    <meta http-equiv='refresh' content='5'>
{% endblock %}

{% block content %}
    <div class='jumbotron col-md-10'>
	<h1>{{ message|random }}<br><span class='text-primary'>{{ employee }}</span></h1>
    </div>
{% endblock %}

templates/worktime/employee.html
{% extends 'worktime/base.html' %}
{% load staticfiles %}

{% block title %}Сотрудники{% endblock %}

{% block content %}

    {% block alphabet %}
        {% include 'worktime/toolbar.html' %}
    {% endblock %}

    <table class='table table-striped tablesorter'>
    <thead>
        <tr>
            <th></th>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Должность</th>
            <th>Компания</th>
            <th>Начало смены</th>
            <th>Конец смены</th>
            <th>Карта сотрудника</th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
    {% for employee in employee_table %}
        <tr>
            <td>{{ forloop.counter }}
            <td>{{ employee.lastname }}</td>
            <td>{{ employee.firstname }}</td>
            <td>{{ employee.post }}</td>
            <td>{{ employee.company}}</td>
            <td>{{ employee.start_work }}</td>
            <td>{{ employee.end_work }}</td>
            <td>{{ employee.card }}</td>
            <td><a href='{% url 'employee_update' employee.id%}'>Ред</a></td>
            <td><a href='{% url 'employee_delete' employee.id%}' class='text-danger'>Удалить</a></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>

    <script src="{% static 'worktime/js/tablesorter.js' %}"></script>

{% endblock %}

templates/worktime/employee_delete.html
{% extends 'worktime/base.html' %}

{% block title %}Удалить сотрудника{% endblock %}

{% block content %}
    <div class='row'>
	<div class='col-md-offset-4 col-md-4'>
	    <h3>Удалить сотрудника {{ object }}?</h3>
	    <form action='' method='post'>
            {% csrf_token %}
            <button type='submit' class='btn btn-danger'>Удалить</button>
	    </form>
	</div>
    </div>
{% endblock %}

templates/worktime/employee_update.html
{% extends 'worktime/base.html' %}

{% block title %}Редактировать сотрудника{% endblock %}

{% block content %}
    <div class='row'>
	<div class='col-md-offset-4 col-md-4'>
	    <h3>Редактировать сотрудника</h3>
	    <form action='' method='post'>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    <span class="text-danger">{{ field.errors }}</span>
                    {{ field }}
                </div>
            {% endfor %}
            <button type='submit' class='btn btn-primary'>Сохранить</button>
	    </form>
	</div>
    </div>
{% endblock %}

templates/worktime/error.html
{% extends 'worktime/base.html' %}

{% block meta %}
    <meta http-equiv='refresh' content='5'>
{% endblock %}

{% block content %}
    <div class='jumbotron col-md-10'>
    {% if card %}
        <h1><span class='text-danger'>Карта {{ card }} зарегистрирована на несколько сотрудников!</span><br>Обратитесь в "Отдел кадров"</h1>
    {% else %}
	    <h1><span class='text-danger'>Произошла ошибка!!!</span><br>Обратитесь в "Отдел кадров"</h1>
    {% endif %}
    </div>
{% endblock %}

templates/worktime/hello.html
{% extends 'worktime/base.html' %}

{% block meta %}
    <meta http-equiv='refresh' content='5'>
{% endblock %}

{% block content %}
    <div class='jumbotron col-md-10'>
	<h1>{{ message }}<br><span class='text-primary'>{{ employee }}</span></h1>
    </div>
{% endblock %}

templates/worktime/index.html
{% extends 'worktime/base.html' %}

{% block title %}Учет времени{% endblock %}

{% block content %}

    <div class='jumbotron col-md-10'>
	<h1 id='clock'></h1>
    <h2 id='date'></h2>
	<br>
	<br>
	<form action='{% url 'index' %}' method='post'>
	    <div class='form-group'>
		{% csrf_token %}
		<input type='text' class='form-control input-lg' placeholder='Карта сотрудника' name='card' autocomplete='off' autofocus>
	    </div>
	</form>
    </div>
    
    <script>
	    function Clock() {
            var date = new Date();
            var hours = date.getHours();
            var minutes = date.getMinutes();
            var seconds = date.getSeconds();
            var options = {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
                weekday: 'long'
            };
            if (hours < 10) hours = '0' + hours;
            if (minutes < 10) minutes = '0' + minutes;
            if (seconds < 10) seconds = '0' + seconds;
            document.getElementById('clock').innerHTML = hours + ':' + minutes + ':' + seconds;
            document.getElementById('date').innerHTML = date.toLocaleString("ru", options);
	    }
	    window.onload = function () {
	        setInterval(Clock, 1000);
	    };
    </script>

{% endblock %}

templates/worktime/menu.html
{% block menu %}

{% if user.is_authenticated %}
    <div class='col-sm-3 col-md-2 sidebar'>
        <ul class='nav nav-sidebar'>
            <li>
                <a href='{% url 'index' %}'>
                    <span class='glyphicon glyphicon-home'></span>  Начальная страница
                </a>
            </li>
            <li class={% if 'tabel' in request.path %}'active'{% endif %}>
                <a href='{% url 'tabel' current_year current_month current_day %}'>
                    <span class='glyphicon glyphicon-calendar'></span>  Табель
                </a>
            </li>
{#            <li class={% if 'tabel_period' in request.path %}'active'{% endif %}>#}
{#                <a href='{% url 'tabel_period_form' %}'>#}
{#                    <span class='glyphicon glyphicon-calendar'></span>  Табель за период#}
{#                </a>#}
{#            </li>#}
            <li class={% if 'employee' in request.path and not 'employee_create' in request.path %}'active'{% endif %}>
                <a href='{% url 'employee' %}'>
                    <span class='glyphicon glyphicon-user'></span>  Сотрудники
                </a>
            </li>
            <li class={% if 'employee_create' in request.path %}'active'{% endif %}>
                <a href='{% url 'employee_create' %}'>
                    <span class='glyphicon glyphicon-plus'></span>  Добавить сотрудника
                </a>
            </li>
            {% if user.is_staff %}
                <li>
                    <a href='{% url 'admin:index' %}'>
                        <span class='glyphicon glyphicon-dashboard'></span>  Администрирование
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endif %}

{% endblock %}

templates/worktime/period_form.html
{% extends 'worktime/base.html' %}

{% block title %}Выбор периода и сотрудника{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-offset-4 col-lg-offset-4 col-md-4 col-lg-4">
			<h3>Выбрать сотрудника и период</h3>
			<form action="" method="post">
				{% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Показать</button>
			</form>
		</div>
    </div>

    <script>
        $("#id_period").datepicker({
            dateFormat: 'ddmmyy',
            firstDay: 1,
            dayNamesMin: [ 'Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
            onSelect: function( selectedDate ) {
                if(!$(this).data().datepicker.first){
                    $(this).data().datepicker.inline = true;
                    $(this).data().datepicker.first = selectedDate;
                }else{
                    if(selectedDate > $(this).data().datepicker.first){
                        $(this).val($(this).data().datepicker.first+"-"+selectedDate);
                    }else{
                        $(this).val(selectedDate+"-"+$(this).data().datepicker.first);
                    }
                    $(this).data().datepicker.inline = false;
                }
            },
            onClose:function(){
                delete $(this).data().datepicker.first;
                $(this).data().datepicker.inline = false;
            }
        });
    </script>

{% endblock %}

templates/worktime/tabel_form.html
{% extends 'worktime/base.html' %}
{% load staticfiles %}

{% block title %}Выбор периода и сотрудника{% endblock %}

{% block content %}

    <ul class="nav nav-tabs">
        <li role="presentation"><a href="{% url 'tabel' current_year current_month current_day %}"> Табель за сутки</a></li>
        <li role="presentation" class="active"><a href="{% url 'tabel_period_form' %}">Табель за период</a></li>
    </ul>

	<div class="row">
		<div class="col-md-offset-4 col-lg-offset-4 col-md-4 col-lg-4">
			<h3>Выбрать сотрудника и период</h3>
			<form action="" method="post">
				{% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {% if not field.is_hidden %}{{ field.label_tag }}{% endif %}
                        <span class="text-danger">{{ field.errors }}</span>
                        {{ field }}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Показать</button>
			</form>
		</div>
    </div>

    {% block static %}
        <script src="{% static 'worktime/js/autocomplete.js' %}"></script>
        <script src="{% static 'worktime/js/datepicker.js' %}"></script>
    {% endblock %}

{% endblock %}

templates/worktime/tabel_period.html
{% extends 'worktime/base.html' %}

{% block title %}Табель за период{% endblock %}

{% block content %}

    <ul class="nav nav-tabs">
        <li role="presentation"><a href="{% url 'tabel' current_year current_month current_day %}"> Табель за сутки</a></li>
        <li role="presentation" class="active"><a href="{% url 'tabel_period_form' %}">Табель за период</a></li>
    </ul>
    
    <h3>Табель сотрудника: <span class='text-primary'>{{ employee }}</span> с {{ start|date:'j b Y' }} по {{ end|date:'j b Y' }}</h3>
    <table class='table table-striped'>
	<thead>
	    <tr>
		<th>Дата</th>
		<th>Начало смены</th>
		<th>Конец смены</th>
		<th>Длительность смены</th>
	    </tr>
	</thead>
	<tbody>
	    {% for tabel in tabel_period %}
	    <tr>
		<td>{{ tabel.start_work|date:'j F Y(D)' }}</td>
		<td>{{ tabel.start_work|time:'H:i' }}</td>
		<td>{% if tabel.end_work %}{{ tabel.end_work|time:'H:i' }}{% endif %}</td>
		<td>{% if tabel.time_at_work %}{{ tabel.time_at_work }}{% endif %}</td>
	    </tr>
	    {% endfor %}
	</tbody>
    </table>

{% endblock %}